reducer_config:
    shape_reducer_hdbscan:
        shape: rotateRectangle
        min_cluster_size: 2
        min_samples: 2
        max_eps: 0.1,
        allow_single_cluster: True
        metric_type: IoU
