T1.answers.0.label: Yes, there is at least one jet in this video.
T1.answers.1.label: No, there is no solar jet in this video.
T1.question: Do you see one or several jet(s) in this video?
T2.answers.0.label: 'Yes'
T2.answers.1.label: 'No'
T2.question: Is there another jet in this video?
T5.answers.0.label: 'Yes'
T5.answers.1.label: 'No'
T5.question: "Do you see more than two jets in this video?      \nWe will not annotate\
    \ more than two jets per video, but we would still like to know!"
