T1.instruction: "Go to the frame in the movie strip in which a jet first appears.\
    \ If there are two jets in the movie strip just pick either to start with.\n\n\
    In that frame,  use the first tool to mark the base of the jet (position on the\
    \ Sun from which the jet launches).\n\nNext, go to the frame in the movie strip\
    \ in which this first jet is last visible.\n\nIn that frame,  use the second tool\
    \ to mark the **base of the jet**.\n\nFinally, go to the frame where this first\
    \ jet has the maximum jet length. \n\nIn that frame,  use the last tool and draw\
    \ a box from the base of the jet to the tip of the jet. Then rotate and size the\
    \ box to best fit the jet even if its curved."
T1.tools.0.label: Base of Jet 1 in frame where it **first appears**
T1.tools.1.label: Base of Jet 1 in frame where it's **last visible**
T1.tools.2.label: Box Jet 1
T3.answers.0.label: 'Yes'
T3.answers.1.label: 'No'
T3.question: 'Play the movie by clicking on the "play" button, below the image, on
    the left:


    ![play.png](https://panoptes-uploads.zooniverse.org/project_attached_image/e015ba28-e7f3-4f28-a860-971700d8c7e2.png
    =300x)


    Do you see one or several jets in this movie strip?'
T4.answers.0.label: 'Yes'
T4.answers.1.label: 'No'
T4.question: Is there a second jet to mark?
T5.instruction: "Second Jet!! If you found two jets in the movie strip, do the same\
    \ actions you did for the first jet, but make sure you do them on the other jet!\n\
    \nGo to the frame in the movie strip in which the second jet first appears. \n\
    \nIn that frame,  use the first tool to mark the base of the jet.\n\nNext, go\
    \ to the frame in the movie strip in which this second jet is last visible.\n\n\
    In that frame,  use the second tool to mark the **base of the jet**.\n\nFinally,\
    \ go to the frame where this second jet has the maximum jet length.  \n\nIn that\
    \ frame,  use the last tool and draw a box from the base of the jet to the tip\
    \ of the jet. Then rotate and size the box to best fit the jet even if its curved."
T5.tools.0.label: Base of Jet 2 in frame where it **first appears**
T5.tools.1.label: Base of Jet 2 in frame where it's **last visible**
T5.tools.2.label: Box Jet 2
